Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -78,12 +78,22 @@ jobs:
         run: |
           echo "🚀 Integrating KernelSU-Next..."
           cd "${{ env.KERNEL_DIR }}"
-          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s main
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s nongki
           if ! grep -q "CONFIG_KSU=y" arch/arm64/configs/${{ env.DEFCONFIG }}; then
             echo "CONFIG_KSU=y" >> arch/arm64/configs/${{ env.DEFCONFIG }}
           fi
           echo "✅ KernelSU-Next integrated and CONFIG_KSU enabled."
+           if ! grep -q "path_umount" fs/namespace.c 2>/dev/null; then
+           echo "⚙️ Adding dummy path_umount() to fix KernelSU Next link error..."
+            cat >> fs/namespace.c <<'EOF'
 
+           /* Added automatically for KernelSU-Next build fix */
+           int path_umount(struct path *path, int flags)
+           {
+           return 0; /* safely bypass */
+          }
+            EOF
+            fi
       - name: Patch SELinux mode (normal / permissive / disable)
         run: |
           cd "${{ env.KERNEL_DIR }}"
